---
 environment: production
 chdir: /srv/www/api-beeline-inspector
 address: 10.191.1.71
 user: rails
 group: rails
 port: 3000
 pid: /srv/www/api-beeline-inspector/tmp/pids/thin.pid
 rackup: /srv/www/api-beeline-inspector/config.ru
 log: /srv/www/api-beeline-inspector/log/thin.log
 max_conns: 1024
 timeout: 640
 max_persistent_conns: 512
 daemonize: true
